# YAML Linting Configuration
# Validates YAML syntax and best practices

extends: default

rules:
  # Line length - allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Indentation - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments
  comments:
    min-spaces-from-content: 2

  # Document start (---) not required
  document-start:
    present: false

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2

  # Key duplicates
  key-duplicates: enable

  # Truthy values (yes/no/on/off)
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false

# Ignore specific files
ignore: |
  .github/
  node_modules/
  venv/
  __pycache__/
  docs/
  .wiki/
